import type { Ods } from "./ods-ocad";

export const ODS_TITULOS_EN: Record<
  number,
  { titulo: string; descricaoCurta: string }
> = {
  1: { titulo: "No Poverty", descricaoCurta: "End poverty in all its forms, everywhere" },
  2: { titulo: "Zero Hunger", descricaoCurta: "End hunger, achieve food security and improved nutrition and promote sustainable agriculture" },
  3: { titulo: "Good Health and Well-being", descricaoCurta: "Ensure healthy lives and promote well-being for all, at all ages" },
  4: { titulo: "Quality Education", descricaoCurta: "Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all" },
  5: { titulo: "Gender Equality", descricaoCurta: "Achieve gender equality and empower all women and girls" },
  6: { titulo: "Clean Water and Sanitation", descricaoCurta: "Ensure availability and sustainable management of water and sanitation for all" },
  7: { titulo: "Affordable and Clean Energy", descricaoCurta: "Ensure access to affordable, reliable, sustainable and modern energy for all" },
  8: { titulo: "Decent Work and Economic Growth", descricaoCurta: "Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all" },
  9: { titulo: "Industry, Innovation and Infrastructure", descricaoCurta: "Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation" },
  10: { titulo: "Reduced Inequalities", descricaoCurta: "Reduce inequality within and among countries" },
  11: { titulo: "Sustainable Cities and Communities", descricaoCurta: "Make cities and human settlements inclusive, safe, resilient and sustainable" },
  12: { titulo: "Responsible Consumption and Production", descricaoCurta: "Ensure sustainable consumption and production patterns" },
  13: { titulo: "Climate Action", descricaoCurta: "Take urgent action to combat climate change and its impacts" },
  14: { titulo: "Life Below Water", descricaoCurta: "Conserve and sustainably use the oceans, seas and marine resources for sustainable development" },
  15: { titulo: "Life on Land", descricaoCurta: "Protect, restore and promote sustainable use of terrestrial ecosystems" },
  16: { titulo: "Peace, Justice and Strong Institutions", descricaoCurta: "Promote peaceful and inclusive societies for sustainable development" },
  17: { titulo: "Partnerships for the Goals", descricaoCurta: "Strengthen the means of implementation and revitalize the Global Partnership for Sustainable Development" },
  18: { titulo: "Ethnic-Racial Equality", descricaoCurta: "Eliminate racism and ethnic-racial discrimination against indigenous and Afro-descendant peoples" },
};

export const ODS_EN: Ods[] = [
  {
    numero: 1,
    titulo: ODS_TITULOS_EN[1].titulo,
    descricaoCurta: ODS_TITULOS_EN[1].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "1.2.1", descricao: "Proportion of population living below the national poverty line, by sex, age, employment status and geographical location (urban/rural).", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "1.2.2", descricao: "Proportion of men, women and children of all ages living in poverty in all dimensions according to national definitions", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "1.3.1", descricao: "Proportion of population covered by social protection systems, by sex, and for the following population groups: children, unemployed population, elderly population, persons with disabilities, pregnant women, newborns, people who suffered work accidents, population at risk of poverty and other vulnerable population groups", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "1.4.1", descricao: "Proportion of population living in households with access to basic services", status: "Em análise/construção", eixos: ["Saúde", "Assistência Social"] },
      { codigo: "1.a.2", descricao: "Proportion of total public spending on essential services (education, health and social protection)", status: "Em análise/construção", eixos: ["Educação", "Saúde", "Assistência Social"] },
      { codigo: "1.b.1", descricao: "Public social spending in favour of the poor", status: "Em análise/construção", eixos: ["Assistência Social"] },
    ],
  },
  {
    numero: 2,
    titulo: ODS_TITULOS_EN[2].titulo,
    descricaoCurta: ODS_TITULOS_EN[2].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "2.1.1", descricao: "Prevalence of undernourishment", status: "Produzido", eixos: ["Assistência Social", "Saúde"] },
      { codigo: "2.1.2", descricao: "Prevalence of moderate or severe food insecurity, based on the Food Insecurity Experience Scale", status: "Produzido", eixos: ["Assistência Social", "Saúde"] },
      { codigo: "2.2.1", descricao: "Prevalence of stunting in children under 5 years of age", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "2.2.2", descricao: "Prevalence of malnutrition in children under 5 years of age, by type of malnutrition (underweight and overweight)", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "2.2.3", descricao: "Prevalence of anaemia in women aged 15 to 49, by pregnancy status", status: "Sem dados", eixos: ["Saúde"] },
      { codigo: "2.2.4", descricao: "Prevalence of minimum dietary diversity, by population group (children aged 6 to 23.9 months and non-pregnant women aged 15 to 49 years)", status: "Em análise/construção", eixos: ["Saúde", "Assistência Social"] },
    ],
  },
  {
    numero: 3,
    titulo: ODS_TITULOS_EN[3].titulo,
    descricaoCurta: ODS_TITULOS_EN[3].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "3.1.1", descricao: "Maternal mortality ratio", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.1.2", descricao: "Proportion of births attended by skilled health personnel", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.2.1", descricao: "Under-five mortality rate", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.2.2", descricao: "Neonatal mortality rate", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.3.1", descricao: "Number of new HIV infections per 1,000 inhabitants, by sex, age and specific populations", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "3.3.2", descricao: "Tuberculosis incidence rate per 100,000 inhabitants", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.3.3", descricao: "Malaria incidence rate per 1,000 inhabitants", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.3.4", descricao: "Hepatitis B incidence rate per 100,000 inhabitants", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.3.5", descricao: "Number of people requiring interventions against neglected tropical diseases (NTDs)", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.4.1", descricao: "Mortality rate attributable to diseases of the circulatory system, malignant tumours, diabetes mellitus and chronic respiratory diseases", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.4.2", descricao: "Suicide mortality rate", status: "Produzido", eixos: ["Saúde", "Assistência Social"] },
      { codigo: "3.5.1", descricao: "Coverage of interventions (pharmacological, psychosocial, rehabilitation and aftercare) for the treatment of substance use disorders", status: "Sem dados", eixos: ["Saúde", "Assistência Social"] },
      { codigo: "3.5.2", descricao: "Total per capita (aged 15 or older) annual consumption of pure alcohol in litres", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.6.1", descricao: "Road traffic mortality rate", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.7.1", descricao: "Proportion of women of reproductive age (15 to 49 years) who use modern methods of family planning", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "3.7.2", descricao: "Number of live births to adolescent mothers (age groups 10-14 and 15-19) per 1,000 women in these age groups", status: "Produzido", eixos: ["Saúde", "Assistência Social"] },
      { codigo: "3.8.1", descricao: "Coverage of essential health services", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "3.8.2", descricao: "Proportion of people in households with large household health expenditures relative to total household expenditures", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.9.1", descricao: "Mortality rate attributed to ambient (outdoor and household) air pollution", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "3.9.2", descricao: "Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.9.3", descricao: "Mortality rate attributed to unintentional poisoning", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.a.1", descricao: "Prevalence of current tobacco use among the population aged 15 years or older", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "3.b.1a", descricao: "Proportion of the target population that received 3 doses of diphtheria, tetanus and pertussis vaccine (DTP3)", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "3.b.1b", descricao: "Proportion of the target population that received the second dose of measles-containing vaccine (MCV2)", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "3.b.1c", descricao: "Proportion of the target population that received the 3rd dose of pneumococcal conjugate vaccine (PCV3)", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "3.b.1d", descricao: "Proportion of the target population that received the final dose of human papillomavirus (HPV) vaccine", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "3.b.1", descricao: "Vaccination coverage rate of the population in relation to vaccines included in the National Immunization Program", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "3.b.2", descricao: "Net total official development assistance for medical research and basic health sectors", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "3.b.3", descricao: "Index of Access to Health Products", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "3.c.1", descricao: "Number of health workers per inhabitant", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "3.d.1", descricao: "Capacity for the International Health Regulations (IHR) and health emergency preparedness", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "3.d.2", descricao: "Percentage of bloodstream infections due to selected antimicrobial-resistant organisms", status: "Em análise/construção", eixos: ["Saúde"] },
    ],
  },
  {
    numero: 4,
    titulo: ODS_TITULOS_EN[4].titulo,
    descricaoCurta: ODS_TITULOS_EN[4].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "4.1.1", descricao: "Proportion of children and young people: (a) in the second and third grades of primary education; (b) at the end of the lower primary years; and c) at the end of the upper primary years, who have achieved at least a minimum level of proficiency in (i) reading and (ii) mathematics, by sex", status: "Em análise/construção", eixos: ["Educação"] },
      { codigo: "4.1.2", descricao: "Completion rate of primary and secondary education", status: "Produzido", eixos: ["Educação"] },
      { codigo: "4.2.1", descricao: "Proportion of children aged 24-59 months who are on track in health, learning and psychosocial development, by sex", status: "Sem dados", eixos: ["Educação", "Saúde"] },
      { codigo: "4.2.2", descricao: "Participation rate in organized learning (one year before the official primary entry age), by sex", status: "Produzido", eixos: ["Educação"] },
      { codigo: "4.3.1", descricao: "Participation rate of youth and adults in formal and non-formal education in the previous 12 months, by sex", status: "Sem dados", eixos: ["Educação"] },
      { codigo: "4.4.1", descricao: "Proportion of youth and adults with information and communications technology (ICT) skills, by type of skill", status: "Sem dados", eixos: ["Educação"] },
      { codigo: "4.5.1", descricao: "Parity indices (women/men, rural/urban, 1st/5th wealth quintiles and others such as persons with disabilities, indigenous populations and conflict-affected populations, as data are available) for all indicators in this list that can be disaggregated", status: "Produzido", eixos: ["Educação"] },
      { codigo: "4.6.1", descricao: "Youth/adult literacy rate", status: "Produzido", eixos: ["Educação"] },
      { codigo: "4.7.1", descricao: "Extent to which (i) global citizenship education and (ii) education for sustainable development are integrated into (a) national education policies; (b) school curricula; (c) teacher training; and (d) student assessment", status: "Em análise/construção", eixos: ["Educação"] },
      { codigo: "4.a.1", descricao: "Proportion of schools with access to: (a) electricity; (b) the Internet for pedagogical purposes; (c) computers for pedagogical purposes; (d) infrastructure and materials adapted for students with disabilities; (e) drinking water; (f) single-sex sanitation facilities; and (g) basic handwashing facilities (in accordance with the definitions of the WASH indicators)", status: "Produzido", eixos: ["Educação", "Saúde"] },
      { codigo: "4.c.1", descricao: "Proportion of teachers who received the required minimum qualification, by level of education", status: "Produzido", eixos: ["Educação"] },
    ],
  },
  {
    numero: 5,
    titulo: ODS_TITULOS_EN[5].titulo,
    descricaoCurta: ODS_TITULOS_EN[5].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "5.2.1", descricao: "Proportion of women and girls aged 15 years and older who experienced physical, sexual or psychological violence by a current or former intimate partner in the previous 12 months, by form of violence and by age", status: "Em análise/construção", eixos: ["Assistência Social", "Saúde"] },
      { codigo: "5.2.2", descricao: "Proportion of women and girls aged 15 years and older who experienced sexual violence by other non-intimate partners in the previous 12 months, by age and place of occurrence", status: "Em análise/construção", eixos: ["Assistência Social", "Saúde"] },
      { codigo: "5.4.1", descricao: "Proportion of time spent on unpaid domestic and care work, by sex, age and location", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "5.6.1", descricao: "Proportion of women aged between 15 and 49 years who make informed decisions about their sexual relations, use of contraceptives and reproductive health care", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "5.6.2", descricao: "Number of countries with legislation and regulations that guarantee full and equal access of women and men aged 15 years or older to sexual and reproductive health care, information and education", status: "Sem dados", eixos: ["Saúde"] },
    ],
  },
  {
    numero: 6,
    titulo: ODS_TITULOS_EN[6].titulo,
    descricaoCurta: ODS_TITULOS_EN[6].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "6.1.1", descricao: "Proportion of population using safely managed drinking water services", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "6.2.1", descricao: "Proportion of population using (a) safely managed sanitation services and (b) facilities for handwashing with water and soap", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "6.3.1", descricao: "Proportion of domestic and industrial wastewater flows safely treated", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "6.3.2", descricao: "Proportion of bodies of water with good ambient water quality", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "6.4.1", descricao: "Change in water-use efficiency over time", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "6.4.2", descricao: "Level of water stress: proportion of freshwater withdrawals relative to total available freshwater resources", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "6.5.1", descricao: "Degree of implementation of integrated water resources management (0-100)", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "6.5.2", descricao: "Proportion of transboundary watershed areas covered by an operational agreement for water cooperation", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "6.6.1", descricao: "Change in the extent of water-related ecosystems over time", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "6.a.1", descricao: "Amount of official development assistance in the area of water and sanitation, embedded in a government expenditure plan", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "6.b.1", descricao: "Participation of local communities in water and sanitation management", status: "Produzido", eixos: ["Saúde", "Assistência Social"] },
    ],
  },
  {
    numero: 7,
    titulo: ODS_TITULOS_EN[7].titulo,
    descricaoCurta: ODS_TITULOS_EN[7].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "7.1.1", descricao: "Percentage of population with access to electricity", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "7.1.2", descricao: "Percentage of population with primary reliance on clean fuels and technologies", status: "Produzido", eixos: ["Saúde"] },
    ],
  },
  {
    numero: 8,
    titulo: ODS_TITULOS_EN[8].titulo,
    descricaoCurta: ODS_TITULOS_EN[8].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "8.5.1", descricao: "Real average hourly earnings of persons aged 15 years or older employed in the reference week with labour income, usually received in all jobs, by sex, age group, occupational group of the main job and disability status", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "8.5.2", descricao: "Unemployment rate, by sex, age group and disability status", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "8.6.1", descricao: "Percentage of people aged 15 to 24 who are not employed, not in education and not in training for a job", status: "Produzido", eixos: ["Educação", "Assistência Social"] },
      { codigo: "8.7.1", descricao: "Proportion and number of children aged 5-17 engaged in child labour, by sex and age", status: "Produzido", eixos: ["Assistência Social", "Educação"] },
      { codigo: "8.b.1", descricao: "Existence of a developed and operationalized national strategy for youth employment, as a stand-alone strategy or as part of a national employment strategy", status: "Em análise/construção", eixos: ["Assistência Social"] },
    ],
  },
  {
    numero: 9,
    titulo: ODS_TITULOS_EN[9].titulo,
    descricaoCurta: ODS_TITULOS_EN[9].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "9.c.1", descricao: "Proportion of population covered by a mobile network, by type of technology", status: "Produzido", eixos: ["Educação"] },
      { codigo: "9.1.1", descricao: "Proportion of the rural population living within a 2 km radius of access to an all-season road", status: "Sem dados", eixos: ["Saúde"] },
    ],
  },
  {
    numero: 10,
    titulo: ODS_TITULOS_EN[10].titulo,
    descricaoCurta: ODS_TITULOS_EN[10].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "10.1.1", descricao: "Growth rate of household expenditure or income per capita of the bottom 40 per cent of the population relative to the total population", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "10.2.1", descricao: "Proportion of people living below 50 per cent of median income, by sex, age and persons with disabilities", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "10.4.1", descricao: "Proportion of labour compensation in GDP, including wages and social protection transfers", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "10.4.2", descricao: "Redistributive impact of fiscal policy", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "10.7.4", descricao: "Proportion of the refugee population, by country of origin", status: "Produzido", eixos: ["Assistência Social"] },
    ],
  },
  {
    numero: 11,
    titulo: ODS_TITULOS_EN[11].titulo,
    descricaoCurta: ODS_TITULOS_EN[11].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "11.1.1", descricao: "Proportion of urban population living in slums, informal settlements or inadequate housing", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "11.2.1", descricao: "Proportion of population that has adequate access to public transport, by sex, age and persons with disabilities", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "11.3.2", descricao: "Proportion of cities with a structure for direct participation of civil society in urban planning and management that operates regularly and democratically", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "11.4.1", descricao: "Total per capita expenditure (public and private) spent on the preservation, protection and conservation of all cultural and natural heritage, by type of heritage", status: "Produzido", eixos: ["Educação"] },
      { codigo: "11.6.1", descricao: "Proportion of urban solid waste collected and managed in controlled facilities out of the total urban waste generated, by cities", status: "Produzido", eixos: ["Saúde"] },
      { codigo: "11.6.2", descricao: "Average annual level of inhalable particles (e.g. with a diameter below 2.5 µm and 10 µm) in cities (population weighted)", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "11.7.1", descricao: "Proportion of built-up area in cities that is open public space for use by all, by sex, age and persons with disabilities", status: "Sem dados", eixos: ["Educação", "Assistência Social"] },
      { codigo: "11.7.2", descricao: "Proportion of the population victim of physical or sexual harassment, by sex, age group, persons with disabilities and place of occurrence, in the previous 12 months", status: "Sem dados", eixos: ["Assistência Social"] },
      { codigo: "11.a.1", descricao: "Number of countries that have national urban policies or regional development plans that (a) respond to population dynamics; (b) ensure balanced territorial development; and (c) have fiscal responsibility", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "11.b.1", descricao: "Number of countries that adopt and implement national disaster risk reduction strategies in line with the Sendai Framework for Disaster Risk Reduction 2015-2030", status: "Produzido", eixos: ["Saúde", "Assistência Social"] },
      { codigo: "11.b.2", descricao: "Proportion of local governments that adopt and implement local disaster risk reduction strategies in line with national disaster risk reduction strategies", status: "Produzido", eixos: ["Saúde", "Assistência Social"] },
      { codigo: "11.c.1", descricao: "Total official development assistance and other official flows for urban infrastructure or urban infrastructure projects, by sector", status: "Em análise/construção", eixos: ["Saúde"] },
    ],
  },
  {
    numero: 12,
    titulo: ODS_TITULOS_EN[12].titulo,
    descricaoCurta: ODS_TITULOS_EN[12].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "12.8.1", descricao: "Extent to which (i) global citizenship education and (ii) education for sustainable development are integrated into (a) national education policies; (b) school curricula; (c) teacher training; and (d) student assessment", status: "Sem dados", eixos: ["Educação"] },
    ],
  },
  {
    numero: 13,
    titulo: ODS_TITULOS_EN[13].titulo,
    descricaoCurta: ODS_TITULOS_EN[13].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "13.3.1", descricao: "Extent to which (i) global citizenship education and (ii) education for sustainable development are integrated into (a) national education policies; (b) school curricula; (c) teacher training; and (d) student assessment", status: "Sem dados", eixos: ["Educação"] },
    ],
  },
  {
    numero: 14,
    titulo: ODS_TITULOS_EN[14].titulo,
    descricaoCurta: ODS_TITULOS_EN[14].descricaoCurta,
    indicadoresContemplados: [],
  },
  {
    numero: 15,
    titulo: ODS_TITULOS_EN[15].titulo,
    descricaoCurta: ODS_TITULOS_EN[15].descricaoCurta,
    indicadoresContemplados: [],
  },
  {
    numero: 16,
    titulo: ODS_TITULOS_EN[16].titulo,
    descricaoCurta: ODS_TITULOS_EN[16].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "16.1.1", descricao: "Number of victims of intentional homicide, per 100,000 inhabitants, by sex and age", status: "Produzido", eixos: ["Assistência Social", "Saúde"] },
      { codigo: "16.1.3", descricao: "Proportion of the population subjected to physical, psychological or sexual violence in the previous 12 months", status: "Produzido", eixos: ["Assistência Social", "Saúde"] },
      { codigo: "16.1.4", descricao: "Proportion of the population that feels safe when walking alone in the area where they live", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "16.2.1", descricao: "Proportion of children aged between 1 and 17 years who suffered any physical punishment and/or psychological aggression by caregivers in the last month", status: "Sem dados", eixos: ["Assistência Social"] },
      { codigo: "16.2.2", descricao: "Number of victims of trafficking in persons per 100,000 inhabitants, by sex, age and form of exploitation", status: "Sem dados", eixos: ["Assistência Social"] },
      { codigo: "16.2.3", descricao: "Proportion of young women and men aged between 18 and 29 years who were victims of sexual violence up to the age of 18", status: "Em análise/construção", eixos: ["Assistência Social", "Saúde"] },
      { codigo: "16.3.1", descricao: "Proportion of victims of violence in the previous 12 months who reported it to the competent authorities or to other officially recognized conflict resolution bodies", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "16.3.2", descricao: "Proportion of pretrial detainees in relation to the total prison population", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "16.6.1", descricao: "Primary public expenditures as a proportion of the originally approved budget, by sector (or by budget codes or similar)", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "16.7.1", descricao: "Proportions of positions (by sex, age, persons with disabilities and population groups) in public institutions (national and local legislatures, public administration and courts) in relation to national distributions", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "16.7.2", descricao: "Proportion of the population that considers decision-making processes to be inclusive and responsive, by sex, age, disability and population group", status: "Sem dados", eixos: ["Assistência Social"] },
      { codigo: "16.9.1", descricao: "Proportion of children under 5 years whose births were registered by a civil authority, by age", status: "Produzido", eixos: ["Assistência Social"] },
      { codigo: "16.10.1", descricao: "Number of verified cases of killing, kidnapping, enforced disappearance, arbitrary detention and torture of journalists, media personnel, trade unionists and human rights defenders in the previous 12 months", status: "Sem dados", eixos: ["Assistência Social"] },
      { codigo: "16.10.2", descricao: "Number of countries that adopt and implement constitutional, statutory and/or policies for public access to information", status: "Produzido", eixos: ["Assistência Social", "Educação"] },
      { codigo: "16.a.1", descricao: "Existence of national independent human rights institutions, in accordance with the Paris Principles", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "16.b.1", descricao: "Proportion of the population that reported having felt personally discriminated against or harassed in the previous 12 months on grounds of discrimination prohibited under international human rights law", status: "Sem dados", eixos: ["Assistência Social"] },
    ],
  },
  {
    numero: 17,
    titulo: ODS_TITULOS_EN[17].titulo,
    descricaoCurta: ODS_TITULOS_EN[17].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "17.18.1", descricao: "Statistical capacity indicator for monitoring the Sustainable Development Goals", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "17.19.1", descricao: "Value in dollars of all resources made available to strengthen statistical capacity in developing countries", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "17.19.2", descricao: "Proportion of countries that (a) carried out at least one Population and Housing Census in the last 10 years; and (b) achieved 100% birth registration and 80% death registration", status: "Produzido", eixos: ["Assistência Social"] },
    ],
  },
  {
    numero: 18,
    titulo: ODS_TITULOS_EN[18].titulo,
    descricaoCurta: ODS_TITULOS_EN[18].descricaoCurta,
    indicadoresContemplados: [
      { codigo: "18.1.3", descricao: "Average monthly income of workers by race/color, ethnicity, sex and territory, by occupational group and education level", status: "Em análise/construção", eixos: ["Educação", "Assistência Social"] },
      { codigo: "18.2.1", descricao: "Rate of victims of intentional homicide, per 100,000 inhabitants, by sex, age and color/race", status: "Em análise/construção", eixos: ["Assistência Social", "Saúde"] },
      { codigo: "18.2.2", descricao: "Proportion of the population by sex and color/race subjected to physical, psychological or sexual violence in the previous 12 months", status: "Em análise/construção", eixos: ["Assistência Social", "Saúde"] },
      { codigo: "18.2.3", descricao: "Number of deaths resulting from police interventions by sex, age group and color/race", status: "Em análise/construção", eixos: ["Assistência Social", "Saúde"] },
      { codigo: "18.2.4", descricao: "Rate of homicides of women and girls inside and outside residences by race/color", status: "Em análise/construção", eixos: ["Assistência Social", "Saúde"] },
      { codigo: "18.2.5", descricao: "Number of cases of violence against LGBTQIAPN+ persons by color/race and age", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.2.6", descricao: "Number of homicides against LGBTQIAPN+ persons by color/race and age", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.2.7", descricao: "Number of reports of hate crimes associated with racism and racial insult and misogyny, including crimes committed in virtual environments, in relation to indigenous and Afro-descendant populations", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.3.1", descricao: "Distribution of incarcerated persons by race/color, age, ethnicity, sex and type of crime", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.3.2", descricao: "Distribution of incarcerated persons without conviction by race/color, age, ethnicity and sex", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.3.3", descricao: "Number of cases related to racism/racial insult, religious intolerance, homophobia and transphobia", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.3.4", descricao: "Proportion of people residing in municipalities with legal aid potential provided by the Public Defender's Office by color/race", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.3.5", descricao: "Proportion of the population that feels safe when walking alone in the area where they live, by color/race and sex", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.4.1", descricao: "Proportion of seats occupied by sex and color/race in the Executive branch (governor, mayor) and Legislature (senator, federal representative, state/district representative, city council member)", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.4.2", descricao: "Proportion of people who run for elections (executive/legislative candidates), by color/race, ethnicity and sex, gender identity and sexual orientation, type of financing", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.4.3", descricao: "Proportion of female and male public servants by color/race, ethnicity, sex, gender identity, sexual orientation and level of the Brazilian Classification of Occupations (CBO) across the three branches of government", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.4.4", descricao: "Proportion of mid-level and senior positions in the public sector occupied, by color/race, ethnicity, sex, gender identity and sexual orientation", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.4.5", descricao: "Proportion of employees in the private sector by color/race, ethnicity, sex, gender identity, sexual orientation, by remuneration, type of occupation and type of position", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.4.6", descricao: "Proportion of seats in collegiate bodies and participation instances occupied in corporate boards of companies x public/private, by color/race, ethnicity, sex, gender identity and sexual orientation", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.5.1", descricao: "Indigenous or quilombola persons residing in regularized territories", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.5.2", descricao: "Indigenous or quilombola persons in families registered in the Unified Registry (Cadastro Único) for social programs", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.5.6", descricao: "Population in areas at risk of geological disasters by race/color", status: "Em análise/construção", eixos: ["Saúde", "Assistência Social"] },
      { codigo: "18.6.1", descricao: "Indigenous or quilombola residents in households with an adequate water supply", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.6.2", descricao: "Households with at least one indigenous or quilombola person with inadequate sanitation", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.6.3", descricao: "Proportion of urban population living in slums, informal settlements or inadequate housing", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.6.4", descricao: "Percentage of people experiencing homelessness who received some type of shelter (shelters, Pop Centers, CRA, CREAS or other government institutions)", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.6.5", descricao: "Housing deficit by sex and color/race according to the head of household", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.7.1", descricao: "Proportion of live births to mothers who had 7 or more prenatal care visits", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.7.2", descricao: "Percentage of the Afro-descendant population covered by primary care teams, including Family Health teams", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.7.3", descricao: "Percentage of the indigenous population covered by Indigenous Health Multiprofessional Teams (EMSI)", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.7.4", descricao: "Proportion of growth and development follow-up consultations for children carried out in accordance with the Ministry of Health recommendation up to 2 years of age", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.7.5", descricao: "Vaccination coverage rate of the population in relation to vaccines included in the National Immunization Program, by age groups, race/color/ethnicity", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.7.6", descricao: "Percentage of malignant neoplasm cases in which the interval between diagnosis and the start of treatment exceeds 60 days, by color/race", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.7.7", descricao: "Proportion of municipalities with a specific instance or management body for health actions aimed at the Black population in accordance with the PNSIPN", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.7.8", descricao: "Percentage of people aged 18 years or older who report a diagnosis of mental illness by a health professional, in treatment with psychotherapy or medication or regular follow-up, by color or race and by type of mental illness", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.7.9", descricao: "Percentage of people who had harmful use of alcohol (in the previous 30 days), by race/color, gender and by the existence or not of follow-up in a mental health service", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.7.10", descricao: "Lack of care in a health service for the reason that led the person to seek care, by color/race and gender", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.8.1", descricao: "School attendance rate in basic education among youth aged 15 to 17 by race/color (including indigenous and quilombola) by sex and state (UF)", status: "Em análise/construção", eixos: ["Educação"] },
      { codigo: "18.8.2", descricao: "Age-grade distortion rate by race/color (including indigenous and quilombola) in basic education (disaggregated into EFI, II and EM), by sex and state (UF)", status: "Em análise/construção", eixos: ["Educação"] },
      { codigo: "18.8.3", descricao: "Dropout rate by race/color (including indigenous and quilombola) in basic education (disaggregated into EFI, II and EM), by sex and state (UF)", status: "Em análise/construção", eixos: ["Educação"] },
      { codigo: "18.8.4", descricao: "Proportion of basic education schools that implemented Law 10.639/2003 and 11.465/2008, by state (UF)", status: "Em análise/construção", eixos: ["Educação"] },
      { codigo: "18.8.5", descricao: "SAEB scores of students by race/color (including indigenous and quilombola), by sex and state (UF)", status: "Em análise/construção", eixos: ["Educação"] },
      { codigo: "18.8.6", descricao: "School attendance rate in higher education by race/color (including indigenous and quilombola), disaggregated by course and type of higher education institution (IES), by sex and state (UF)", status: "Em análise/construção", eixos: ["Educação"] },
      { codigo: "18.8.7", descricao: "Percentage of Black and mixed-race students enrolled by sex and state (UF) in Stricto Sensu Postgraduate Programs", status: "Em análise/construção", eixos: ["Educação"] },
      { codigo: "18.8.8", descricao: "Number and percentage of Black, mixed-race and indigenous people by sex with a Master's and Doctorate degree", status: "Em análise/construção", eixos: ["Educação"] },
      { codigo: "18.8.9", descricao: "Proportion of schools with access to: (a) electricity; (b) the Internet for pedagogical purposes; (c) computers for pedagogical purposes; (d) infrastructure and materials adapted for students with disabilities; (e) drinking water; (f) single-sex sanitation facilities; and (g) basic handwashing facilities (in accordance with the definitions of the WASH indicators)", status: "Em análise/construção", eixos: ["Educação", "Saúde"] },
      { codigo: "18.8.10", descricao: "Percentage of Black, mixed-race and indigenous researchers by sex and state (UF) holding a research productivity fellowship", status: "Em análise/construção", eixos: ["Educação"] },
      { codigo: "18.10.1", descricao: "Percentage of immigrants enrolled in basic education and higher education and in Postgraduate Programs by nationality, sex, race/color and state (UF) and municipalities, according to level of education, in relation to the total number of students", status: "Em análise/construção", eixos: ["Educação"] },
      { codigo: "18.10.2", descricao: "Completion rate of primary and secondary education of immigrant people in Brazil, by race/color and nationality/country of origin", status: "Em análise/construção", eixos: ["Educação"] },
      { codigo: "18.10.3", descricao: "Ratio of immigrants by nationality, race/color and sex with an identified ICD-10 code, by chapter, and the number of sickness benefits granted", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.10.4", descricao: "Ratio between the number of immigrants and the volume of medical occurrences, by ICD, by nationality, race/color and sex, by state and municipality", status: "Em análise/construção", eixos: ["Saúde"] },
      { codigo: "18.10.5", descricao: "Occupancy rate of immigrant people in Brazil, by race/color, sex, level of education and occupational groups, according to age groups", status: "Em análise/construção", eixos: ["Assistência Social"] },
      { codigo: "18.10.6", descricao: "Earnings from all jobs of people residing in Brazil with foreign nationality (or immigrants), by minimum wage classes, according to race/color and sex, level of education and occupational groups", status: "Em análise/construção", eixos: ["Assistência Social"] },
    ],
  },
];
